// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.graph.follow

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GraphFollowNSID = "sh.tangled.graph.follow"
)

func init() {
	util.RegisterType("sh.tangled.graph.follow", &GraphFollow{})
} //
// RECORDTYPE: GraphFollow
type GraphFollow struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.graph.follow" cborgen:"$type,const=sh.tangled.graph.follow"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Subject       string `json:"subject" cborgen:"subject"`
}
