// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.member

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotMemberNSID = "sh.tangled.knot.member"
)

func init() {
	util.RegisterType("sh.tangled.knot.member", &KnotMember{})
} //
// RECORDTYPE: KnotMember
type KnotMember struct {
	LexiconTypeID string  `json:"$type,const=sh.tangled.knot.member" cborgen:"$type,const=sh.tangled.knot.member"`
	AddedAt       *string `json:"addedAt,omitempty" cborgen:"addedAt,omitempty"`
	// domain: domain that this member now belongs to
	Domain string `json:"domain" cborgen:"domain"`
	Member string `json:"member" cborgen:"member"`
}
