// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.policy

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotPolicyNSID = "sh.tangled.knot.policy"
)

func init() {
	util.RegisterType("sh.tangled.knot.policy", &KnotPolicy{})
} //
// RECORDTYPE: KnotPolicy
type KnotPolicy struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.knot.policy" cborgen:"$type,const=sh.tangled.knot.policy"`
	// action: action associated with the key
	Action string `json:"action" cborgen:"action"`
	// domain: domain of the key
	Domain string `json:"domain" cborgen:"domain"`
	// object: object associated with the key
	Object string `json:"object" cborgen:"object"`
	// subject: subject of the key
	Subject string `json:"subject" cborgen:"subject"`
}
