// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.issue.state.open

const ()

const RepoIssueStateOpen = "sh.tangled.repo.issue.state.open"
