// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.publicKey

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PublicKeyNSID = "sh.tangled.publicKey"
)

func init() {
	util.RegisterType("sh.tangled.publicKey", &PublicKey{})
} //
// RECORDTYPE: PublicKey
type PublicKey struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.publicKey" cborgen:"$type,const=sh.tangled.publicKey"`
	// created: key upload timestamp
	Created string `json:"created" cborgen:"created"`
	// key: public key contents
	Key string `json:"key" cborgen:"key"`
	// name: human-readable name for this key
	Name string `json:"name" cborgen:"name"`
}
