// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoNSID = "sh.tangled.repo"
)

func init() {
	util.RegisterType("sh.tangled.repo", &Repo{})
} //
// RECORDTYPE: Repo
type Repo struct {
	LexiconTypeID string  `json:"$type,const=sh.tangled.repo" cborgen:"$type,const=sh.tangled.repo"`
	AddedAt       *string `json:"addedAt,omitempty" cborgen:"addedAt,omitempty"`
	// knot: knot where the repo was created
	Knot string `json:"knot" cborgen:"knot"`
	// name: name of the repo
	Name  string `json:"name" cborgen:"name"`
	Owner string `json:"owner" cborgen:"owner"`
}
