// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bild

// schema: sh.bild.publicKey

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	 util.RegisterType("sh.bild.publicKey", &PublicKey{})
} //
// RECORDTYPE: PublicKey
type PublicKey struct {
	LexiconTypeID string `json:"$type,const=sh.bild.publicKey" cborgen:"$type,const=sh.bild.publicKey"`
	// created: key upload timestamp
	Created string `json:"created" cborgen:"created"`
	// key: public key contents
	Key string `json:"key" cborgen:"key"`
	// name: human-readable name for this key
	Name string `json:"name" cborgen:"name"`
}
